### ISSUE TITLE
Setup the integration

### ISSUE THREAD

**Issue by Maaaaarc** [rcasula/kostalpiko-homeassistant#13]
Hello, 
unfortunately, I have not found how to set up the integration. 
How should the configuration be setup?

I tried different Configs, but none worked.

Thanks in advance

**Comment by rcasula** [comment]
Hi, could you please post the configuration you used?

**Comment by Maaaaarc** [comment]
I used this config:
kostal:
    host: 192.168.178.135
    username: pvserver
    password: pvwr
    monitored_conditions:
      - current_power
      - total_energy
      - daily_energy
      - string1_voltage
      - string1_current
      - string2_voltage
      - string2_current
      - l1_voltage
      - l1_power
      - l2_voltage
      - l2_power
      - l3_voltage
      - l3_power
      - status

**Comment by Maaaaarc** [comment]
Thanks for your fast response.

now it worked halfways.
The Device is added but the  new values are unknown.

These are the logs:
```

![image](https://user-images.githubusercontent.com/83964022/178535495-3662309c-6509-4bc9-91d5-c514435d8f00.png)

**One Error:**
Logger: homeassistant.helpers.entity
Source: custom_components/kostal/sensor.py:130
Integration: Kostal Piko ([documentation](https://github.com/rcasula/kostalpiko-homeassistant))
First occurred: 5:33:22 PM (24 occurrences)
Last logged: 5:44:52 PM

Update for sensor.kostal_piko_current_power fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/config/custom_components/kostal/sensor.py", line 119, in async_update
    await self.hass.async_add_executor_job(self._update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kostal/sensor.py", line 130, in _update
    self._state = data.get_current_power()
  File "/usr/local/lib/python3.10/site-packages/kostalpiko/kostalpiko.py", line 159, in get_current_power
    value = self.safe_get_value('current_power')
  File "/usr/local/lib/python3.10/site-packages/kostalpiko/kostalpiko.py", line 154, in safe_get_value
    if self._raw_data is not None and name in self.indices and self.indices[name] is not None:
AttributeError: 'PikoData' object has no attribute 'indices'
```

**Comment by maubreville** [comment]
Hey. I had the same error and fixed it for our system here. The issue is that the piko replies with an unexpected number of values. Here, the system setup is: 2 strings and 3 phases (L1,L2,L3). This is not yet supported by the kostalpiko library. 

See this PR:

https://github.com/rcasula/kostalpiko/pull/2

**Comment by petos** [comment]
I have the same issue as above. I see the PR is merged and despite of having latest kostalpiko-homeassistant it seems I have old version of kostalpiko. 
The stupid question is, HOW to update this? Thank you

**Comment by axyaxyfr** [comment]
Excuse me for asking a n00b question, but where do I put the config?

**Comment by axyaxyfr** [comment]
I have the same issue, I guess. My log says:
Denne fejl stammer fra en brugerdefineret integration.

Logger: homeassistant.helpers.entity
Source: custom_components/kostal/sensor.py:140
Integration: Kostal Piko (documentation)
First occurred: 10.51.24 (3 occurrences)
Last logged: 10.52.24

Update for sensor.kostal_piko_string_2_voltage fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/config/custom_components/kostal/sensor.py", line 119, in async_update
    await self.hass.async_add_executor_job(self._update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kostal/sensor.py", line 140, in _update
    self._state = data.get_string2_voltage()
  File "/usr/local/lib/python3.10/site-packages/kostalpiko/kostalpiko.py", line 199, in get_string2_voltage
    value = self.safe_get_value('string2_voltage')
  File "/usr/local/lib/python3.10/site-packages/kostalpiko/kostalpiko.py", line 154, in safe_get_value
    if self._raw_data is not None and name in self.indices and self.indices[name] is not None:
AttributeError: 'PikoData' object has no attribute 'indices'


I'll attach a picture of my old Kostal interface. What do I need to put in my kostal.yaml?

TIA


![kostal36](https://user-images.githubusercontent.com/98274455/185085130-bb1cd132-438b-48a0-812f-949010abccde.png)

**Comment by Abildgren** [comment]
> I have the same issue as above. I see the PR is merged and despite of having latest kostalpiko-homeassistant it seems I have old version of kostalpiko. The stupid question is, HOW to update this? Thank you

The easy way is to get the PyPi packet updated (https://pypi.org/project/kostalpiko/) to version 0.5 and the requirement in here to be 0.5.

**Comment by Maaaaarc** [comment]
> > I have the same issue as above. I see the PR is merged and despite of having latest kostalpiko-homeassistant it seems I have old version of kostalpiko. The stupid question is, HOW to update this? Thank you
> 
> The easy way is to get the PyPi packet updated (https://pypi.org/project/kostalpiko/) to version 0.5 and the requirement in here to be 0.5.

Maybe a dumb question, but how can I install it? And configure it?

**Comment by petos** [comment]
I'd like to add I'm using whole image (OS) from home-assistant. The env. I can get is just the VM via SSH plugin...

**Comment by petos** [comment]
Actually the https://pypi.org/project/kostalpiko/#history shows the newest version is 0.4... Also when update the manifest to 0.5, I get the error on configuration/startup -- version is not available (or something like that). I just wonder if some release flag is missing for version...?

**Comment by Abildgren** [comment]
The Pypi pull from this repo https://github.com/rcasula/kostalpiko, but AFAIK no new packet (v0.5) will be created before either the version variable in the setup.py file get set to "0.5". Have made the PR but @rcasula need to merge it

HA updates the pip packets at boot. To update it manually and from something which is not in Pypi on the Home Assistant OS is problematic as the normal SSH plugin does not give you access to the underlaying python installation. You will need to have a different SSH access https://developers.home-assistant.io/docs/operating-system/debugging/ Personally I have not had the time to set this up yet though

**Comment by rcasula** [comment]
Yes, sorry for the late follow up. I was unable to work on it, but I soon as I can I just publish the new version of the library. Then I will update this repo. 
Bear with me for another couple of days. Thank you for you patience!

**Comment by rcasula** [comment]
Hi everyone, I've managed to update the library on PyPi. Please let me know if the problem stil persists.

**Comment by petos** [comment]
> Hi everyone, I've managed to update the library on PyPi. Please let me know if the problem stil persists.

Works now perfectly. Thank you!!!
