### ISSUE TITLE
Error since upodate to 2025.6.0 - task exception

### ISSUE THREAD

**Issue by godofglow** [rcasula/kostalpiko-homeassistant#34]
SInce the update to 2025.6.0 

```
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: homeassistant
Quelle: custom_components/kostal/__init__.py:114
Integration: Kostal Piko (Dokumentation)
Erstmals aufgetreten: 06:54:29 (1 Vorkommnis)
Zuletzt protokolliert: 06:54:29

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/kostal/__init__.py", line 114, in _asyncadd_sensors
    await self.hass.config_entries.async_forward_entry_setup(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```

**Comment by godofglow** [comment]
Fileproblem (file was empty) after update. 
Deinstalled integration and installed it again --> works again.
